name: Auto Commit WF

on:
    schedule:
       - cron: "30 10 * * 1,3,4"
    workflow_dispatch:
        inputs:
            commit_message:
                description: Enter Commit Message
                type: string
                required: false

jobs:
    commit:
        name: Commit Code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Print Date
              run: date >> text.txt

            - name: Setup Git User
              run: |
                  git config user.name "${{ github.repository_owner }}"
                  git config user.email "auwensuyi1@outlook.com"

            - name: Commit Code
              run: |
                git pull -p
                git add .
                git commit -m "${{ inputs.commit_message || 'Commiting Date Change'}}"
                git push --force
